# This is a basic workflow to help you get started with Actions

name: BicepInfra-deployment01

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1.4.2
        with: 
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}
      - name: deploy bicepInfra
        working-directory: '${{ github.workspace }}/src/bicep'
        run: |
          # az deployment group create --what-if -g biceprg02 --template-file ./azwebapp01.bicep --parameters webAppName=bicepwebappp-03 
          # az deployment group create --what-if -g az-bicep-dev-eus-rg --template-file ./AppServicePlan.bicep
            az deployment group create --what-if -g azbicep_dev_eus_rg1 -f ./Main.bicep -p ./main.dev.parameters.json
    
  DeployToDev:
      name: Deploy to Dev 
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request'
      needs: [build]
      environment: development
    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3
        - name: Azure Login
          uses: Azure/login@v1.4.2
          with: 
            creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}
        - name: deploy bicepInfra
          working-directory: '${{ github.workspace }}/src/bicep'
          run: |
            # az deployment group create -g biceprg02 --template-file ./azwebapp01.bicep --parameters webAppName=bicepwebappp-03    
            # az deployment group create -g az-bicep-dev-eus-rg --template-file ./AppServicePlan.bicep
            az deployment group create -g azbicep_dev_eus_rg1 -f ./Main.bicep -p ./main.dev.parameters.json
#####################################################
DeployStaging:
  name: Deploy to Staging 
  if: github.event.ref == 'refs/heads/main'
  needs: [Build]
  runs-on: ubuntu-latest
  environment: 
    name: Staging
    url: 'http://test.myapp.com'
  steps:
    - name: Deploy
      run: echo I am deploying! 
          
DeployProd:
  name: Deploy to Production 
  needs: [DeployStaging]
  runs-on: ubuntu-latest
  environment: 
    name: Production
    url: 'http://www.myapp.com'
  steps:
    - name: Deploy
      run: echo I am deploying!   
            
###############################

  # DeployToProd:
  #   name: Deploy to prod 
  # # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   environment: prod

  # # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v3
  #     - name: Azure Login
  #       uses: Azure/login@v1.4.2
  #       with: 
  #         creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}
  #     - name: deploy bicepInfra
  #       working-directory: '${{ github.workspace }}/src/bicep'
  #       run: |
  #         # az deployment group create -g biceprg02 --template-file ./azwebapp01.bicep --parameters webAppName=bicepwebappp-03    
  #         # az deployment group create -g az-bicep-dev-eus-rg --template-file ./AppServicePlan.bicep
  #         az deployment group create -g azbicep_prd_eus_rg1 -f ./Main.bicep -p ./main.prd.parameters.json
